package com.fpltn.entities;
// Generated Apr 10, 2023, 10:48:36 AM by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "qlmyweb")
public class Product implements java.io.Serializable {

	private Integer id;
	private Danhmuc danhmuc;
	private String name;
	private String gia;
	private Account nguoitao;
	private Date ngaytao;
	private Boolean tinhtrang;
	private String mota;
	private String hinhanh;
	public Product() {
	}

	public Product(Danhmuc danhmuc, String name, String gia,Account nguoitao,Date ngaytao,Boolean tinhtrang,
			String mota) {
		this.danhmuc = danhmuc;
		this.name = name;
		this.gia = gia;
		this.nguoitao = nguoitao;
		this.ngaytao=ngaytao;
		this.tinhtrang = tinhtrang;
		this.mota = mota;
	}
	public Product(Integer id, String name,Danhmuc danhmuc, String gia, Account nguoitao,Date newdate, String mota,Boolean tinhtrang,String hinhanh) {
		this.id = id;
		this.name = name;
		this.danhmuc = danhmuc;
		this.gia = gia;
		this.nguoitao = nguoitao;
		this.ngaytao=newdate;
		this.mota = mota;
		this.tinhtrang = tinhtrang;
		this.hinhanh=hinhanh;
	}

	public Product(String name,Danhmuc danhmuc, String gia, Account nguoitao,Date newdate, String mota,Boolean tinhtrang,String hinhanh) {
		this.name = name;
		this.danhmuc = danhmuc;
		this.gia = gia;
		this.nguoitao = nguoitao;
		this.ngaytao=newdate;
		this.mota = mota;
		this.tinhtrang = tinhtrang;
		this.hinhanh=hinhanh;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "danhmuc")
	public Danhmuc getDanhmuc() {
		return this.danhmuc;
	}

	public void setDanhmuc(Danhmuc danhmuc) {
		this.danhmuc = danhmuc;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gia", length = 10)
	public String getGia() {
		return this.gia;
	}

	public void setGia(String gia) {
		this.gia = gia;
	}


	@Column(name = "tinhtrang")
	public Boolean getTinhtrang() {
		return this.tinhtrang;
	}

	public void setTinhtrang(Boolean tinhtrang) {
		this.tinhtrang = tinhtrang;
	}

	@Column(name = "mota", length = 300)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nguoitao")
	public Account getNguoitao() {
		return this.nguoitao;
	}

	public void setNguoitao(Account nguoitao) {
		this.nguoitao = nguoitao;
	}
	@Column(name = "ngaytao")
	public Date getNgaytao() {
		return this.ngaytao;
	}

	public void setNgaytao(Date nguoitao) {
		this.ngaytao = nguoitao;
	}

	@Column(name = "hinhanh")
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String nguoitao) {
		this.hinhanh = nguoitao;
	}

}
